name: Cron Test

on:
  schedule:
    # Run every Tuesday at 10:30.
    - cron: "30 10 * * 2"

permissions:
  contents: read

jobs:
  prerequisites:
    uses: ./.github/workflows/test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  pyodide:
    uses: ./.github/workflows/pyodide.yml
