name: Export OTel

on:
  workflow_run:
    workflows:
      - "CI"
      - "CD"
      - "Cron Test"
      - "Auto-Merge Dependabot PR"
    types: [completed]

permissions: {}

jobs:
  otel-trace:
    if: ${{ github.event.workflow_run.head_repository.full_name == github.repository }}
    runs-on: ubuntu-slim
    permissions:
      contents: read
      actions: read
      pull-requests: read
      checks: read
    steps:
      - name: Export workflow run's traces
        uses: dash0hq/otel-cicd-action@895874bfae14f840e3032f1a14c3f2b45c93f4af # v4.1.1
        with:
          otlpEndpoint: ${{ vars.HONEYCOMB_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.HONEYCOMB_OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
